#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to listen on port 80 and serve "Hello World!" at the root
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
/usr/sbin/service nginx restart
