#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#     Enables management via the init script.
#     Distributes requests using a round-robin algorithm.

apt-get update
apt-get install -y haproxy

printf %s "
frontend lims24-tech-frontend
        bind *:80
        mode http
        default_backend lims24-tech-backend

backend lims24-tech-backend
        balance roundrobin
        server 49038-web-01 54.88.152.143:80 check
        server 49038-web-02 35.153.16.93:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
exit
service haproxy start
